VARIABLE B_FECHA_NAC DATE 
DECLARE
    V_FECHA_NAC DATE;
    V_ANIO_NAC NUMBER(4);
    V_ANIO_ACTUAL NUMBER(4);
    V_EDAD NUMBER(3);

    V_NOMBRE VARCHAR2(30);
BEGIN 
    --INVOCAR Y ASIGNAR DATOS A LAS VARIABLES BIND
    SELECT FIRST_NAME INTO V_NOMBRE FROM EMPLOYEES WHERE EMPLOYEE_ID=150;
    V_FECHA_NAC := :B_FECHA_NAC;
    V_ANIO_NAC := EXTRACT (YEAR FROM V_FECHA_NAC);
    V_ANIO_ACTUAL := EXTRACT (YEAR FROM SYSDATE);
    V_EDAD:= V_ANIO_ACTUAL - V_ANIO_NAC;
    DBMS_OUTPUT.PUT_LINE('Edad: '|| V_EDAD);
END;

