/*
Recuperar lo ssiguientes datos de un empleado, utilzando su id como filtro,
nombre, apellido, salario, fecha contrato

una vez recuperados los datos, transferirlos hacia una variable RECORD


*/


SET SERVEROUTPUT ON

VAR B_ID_EMP NUMBER(3)

DECLARE
    TYPE DATOS_EMPLEADO IS RECORD
    (
        NOMBRE VARCHAR2(15),
        APELLIDO VARCHAR2(15),
        SALARIO NUMBER(6),
        FECHA_CON DATE
    );

    V_REGISTRO DATOS_EMPLEADO;
    V_ID_EMP NUMBER(3);

BEGIN
    V_ID_EMP:=:B_ID_EMP;
    SELECT FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE INTO V_REGISTRO.NOMBRE,V_REGISTRO.APELLIDO,V_REGISTRO.SALARIO,V_REGISTRO.FECHA_CON
    FROM EMPLOYEES WHERE EMPLOYEE_ID=V_ID_EMP;
    DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_REGISTRO.NOMBRE);
    DBMS_OUTPUT.PUT_LINE('APELLIDO: '||V_REGISTRO.APELLIDO);
    DBMS_OUTPUT.PUT_LINE('SALARIO: '||V_REGISTRO.SALARIO);
    DBMS_OUTPUT.PUT_LINE('FECHA DE CONTRATO: '||V_REGISTRO.FECHA_CON);
END;        