VAR B_ID_EMP NUMBER(3)

DECLARE
    V_NOMBRE VARCHAR2(20);
    V_APELLIDO EMPLOYEES.LAST_NAME%TYPE;
    V_FECHA_CON EMPLOYEES.HIRE_DATE%TYPE;
    V_ANIOS NUMBER(7);
BEGIN
    SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
    INTO V_NOMBRE, V_APELLIDO, V_FECHA_CON
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = :B_ID_EMP;
    DBMS_OUTPUT.PUT_LINE(V_NOMBRE||' '||V_APELLIDO||' '||V_FECHA_CON);
END;


