VAR B_NUM NUMBER(2)

DECLARE
    V_NUMERO NUMBER(1);
BEGIN
    V_NUMERO:= :B_NUM;
    IF V_NUMERO < 0 THEN
        DBMS_OUTPUT.PUT_LINE('ES MENOR QUE CERO');
    ELSIF V_NUMERO = 0 THEN
        DBMS_OUTPUT.PUT_LINE('ES IGUAL A CERO');
    ELSIF V_NUMERO > 0 THEN
        DBMS_OUTPUT.PUT_LINE('ES MAYOR QUE CERO');
    END IF;

END;