SET SERVEROUTPUT ON;

DECLARE
    CURSOR CUR_EMP_DEP(P_ID_DEPTO NUMBER, P_SALARIO NUMBER) IS
        SELECT * FROM EMPLOYEES
        WHERE DEPARTMENT_ID = P_ID_DEPTO
        AND SALARY >= P_SALARIO;

    V_REG_EMP EMPLOYEES%ROWTYPE;

BEGIN
    OPEN CUR_EMP_DEP(30, 3000);
        LOOP
            FETCH CUR_EMP_DEP INTO V_REG_EMP;
            EXIT WHEN CUR_EMP_DEP%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(V_REG_EMP.FIRST_NAME || ' ' || V_REG_EMP.LAST_NAME);
        END LOOP;
    CLOSE CUR_EMP_DEP;

END;









DECLARE
    CURSOR CUR_EMP IS SELECT * FROM EMPLOYEES;
    CURSOR CUR_DEP IS SELECT * FROM DEPARTMENTS;
    V_CONT NUMBER := 0;

BEGIN
    FOR REG_DEP IN CUR_DEP
    LOOP
        V_CONT := 0;
        FOR REG_EMP IN CUR_EMP
        LOOP
            IF REG_EMP.DEPARTMENT_ID = REG_DEP.DEPARTMENT_ID THEN
            V_CONT := V_CONT + 1;
            END IF;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE(REG_DEP.DEPARTMENT_NAME ||' (' || V_CONT || ') EMPLEADOS(AS)');
        DBMS_OUTPUT.PUT_LINE(chr(10));
    END LOOP;
END;
