DECLARE
    CURSOR CUR_SOC IS SELECT * FROM SOCIO; 
    CURSOR CUR_PROD_INV_SOC IS SELECT * FROM PRODUCTO_INVERSION_SOCIO;
    CURSOR CUR_ERR IS SELECT * FROM ERROR_PROCESO;
    V_NRO_SOCIO NUMBER(3);
    v_NRO_SOLIC_PROD NUMBER(6);

BEGIN
    FOR REG_SOC IN CUR_SOC LOOP
    SELECT REG_SOC.NRO_SOCIO, REG_SOC.NRO_SOLIC_PROD INTO
    END LOOP;



END;


