CREATE TABLE CLIENTE(
    IDCLIENTE INT         PRIMARY KEY AUTO_INCREMENT,
    PNOMBRE   VARCHAR(20) NOT NULL,
    APATERNO  VARCHAR(20) NOT NULL,
    AMATERNO  VARCHAR(20) NOT NULL,
    RUT       INT         NOT NULL,
    DV        VARCHAR(1)  NOT NULL,
    CORREO    VARCHAR(30) NOT NULL,
    TELEFONO  VARCHAR(11) NOT NULL
);

INSERT INTO CLIENTE(PNOMBRE,APATERNO,AMATERNO,RUT,DV,CORREO,TELEFONO) VALUES ('Felipe','Novoa','Manriquez',21080811,'6','felipenmq','981641903');
INSERT INTO CLIENTE(PNOMBRE,APATERNO,AMATERNO,RUT,DV,CORREO,TELEFONO) VALUES ('Rivaul','Tavara','Chafloque',20456325,'K','ri.tavara','445324454');
INSERT INTO CLIENTE(PNOMBRE,APATERNO,AMATERNO,RUT,DV,CORREO,TELEFONO) VALUES ('Sebastian','Valdes','Zuniga',23332212,'4','se.valdes','4534344543');
INSERT INTO CLIENTE(PNOMBRE,APATERNO,AMATERNO,RUT,DV,CORREO,TELEFONO) VALUES ('Pamela','Novoa','Manriquez',19307490,'1','pa.novoa','3254324234');
INSERT INTO CLIENTE(PNOMBRE,APATERNO,AMATERNO,RUT,DV,CORREO,TELEFONO) VALUES ('Rodolfo','Novoa','Manriquez',11448211,'0','r.novoas','234234322');

CREATE TABLE EQUIPO(
    IDEQUIPO        INT            PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION     VARCHAR(200)   NOT NULL,
    CPU             VARCHAR(20)    NOT NULL,
    MBDISCODURO     INT            NOT NULL,
    GBRAM           INT            NOT NULL,
    PRECIO          INT            NOT NULL,
    TIPO            INT            NOT NULL,
    POTFUENTE       INT,
    FORMCASE        VARCHAR(10),
    TAMPANTALLA     INT,
    PUERTOSUSB      INT,
    MODELO          VARCHAR(30)   NOT NULL
);

CREATE TABLE VENTAS(
    IDVENTA      INT         PRIMARY KEY AUTO_INCREMENT,
    RUTCLIENTE   VARCHAR(12) NOT NULL,
    NOMBRE       VARCHAR(60) NOT NULL,
    FECHA        TIMESTAMP   NOT NULL,
    IDEQUIPO     INT         NOT NULL,
    IDCLIENTE    INT         NOT NULL,
    FOREIGN KEY(IDcliente)   REFERENCES CLIENTE(IDCLIENTE),
    FOREIGN KEY(IDEQUIPO)    REFERENCES EQUIPO(IDEQUIPO)
    
);



