-- CONECTADO COMO EL USUARIO ADMIN

CREATE USER HR IDENTIFIED BY "Mdy2131-Diurno";

ALTER USER HR DEFAULT TABLESPACE DATA
              QUOTA UNLIMITED ON DATA;

ALTER USER HR TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO HR;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO HR;