SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hola Mundo');
END;


DECLARE
--VARIABLE SE DEFINE USUALMENTE CON V_
--VARIABLES CONSTANTES SE DEFINEN USUALMENTE ON C_
        V_PRIMER_NOMBRE VARCHAR2(10);

BEGIN
        V_PRIMER_NOMBRE := 'PABLO';
        DBMS_OUTPUT.PUT_LINE(V_PRIMER_NOMBRE);
        DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_PRIMER_NOMBRE);
END;


DECLARE
    V_TEXTO VARCHAR2(50);
    
BEGIN
    V_TEXTO :='esto es un texto';
    DBMX.OUTPUT.PUT_LINE(UPPER(V_TEXTO));
    DBMX.OUTPUT.PUT_LINE(LOWER(V_TEXTO));
    DBMX.OUTPUT.PUT_LINE(INITCAP(V_TEXTO));

END;