-- Elimina la tabla si ya existe
DROP TABLE IF EXISTS MEDICO_SERVICIO_COMUNIDAD;

-- Crea la tabla MEDICO_SERVICIO_COMUNIDAD con las columnas y tipos de datos apropiados
CREATE TABLE MEDICO_SERVICIO_COMUNIDAD(
    UNIDAD NOT NULL,
    PNOMBRE NOT NULL,
    SNOMBRE NOT NULL,
    APATERNO NOT NULL,
    APMATERNO NOT NULL,
    TELEFONO NOT NULL,
    CORREO_MEDICO NOT NULL,
    ATENCIONES_MEDICAS INT NOT NULL
)AS SELECT U.NOMBRE AS UNIDAD,
       M.PNOMBRE AS PNOMBRE,
       M.SNOMBRE AS SNOMBRE,
       M.APATERNO AS APATERNO,
       M.AMATERNO AS APMATERNO,
       M.TELEFONO AS TELEFONO,
       CONCAT(SUBSTRING(UPPER(U.NOMBRE), 1, 2), SUBSTRING(LOWER(M.APATERNO), LENGTH(M.APATERNO) - 2, 2), SUBSTRING(M.TELEFONO, 1, LENGTH(M.TELEFONO) - 3), TO_CHAR(M.FECHA_CONTRATO, 'DDMM'), '@medicocktk.cl') AS CORREO_MEDICO,
       COUNT(A.ATE_ID) AS ATENCIONES_MEDICAS
FROM MEDICO M
INNER JOIN UNIDAD U ON U.UNI_ID = M.UNI_ID
INNER JOIN ATENCION A ON A.MED_RUN = M.MED_RUN
GROUP BY U.NOMBRE, M.PNOMBRE, M.SNOMBRE, M.APATERNO, M.AMATERNO, M.TELEFONO, TO_CHAR(M.FECHA_CONTRATO, 'DDMM');
