
package Vista;

import Controlador.ControladorEquipo;
import javax.swing.JOptionPane;

public class FrmEquipo extends javax.swing.JFrame {

    /**
     * Creates new form FrmEquipo
     */
    public FrmEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CPU = new javax.swing.JLabel();
        ram = new javax.swing.JScrollPane();
        txtRam = new javax.swing.JTextPane();
        DiscoDuro = new javax.swing.JLabel();
        Ram = new javax.swing.JLabel();
        precio = new javax.swing.JScrollPane();
        txtPrecio = new javax.swing.JTextPane();
        Precio = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        preguntan1 = new javax.swing.JScrollPane();
        txtPregunta1 = new javax.swing.JTextPane();
        pregunta1 = new javax.swing.JLabel();
        pregunta2 = new javax.swing.JLabel();
        preguntan2 = new javax.swing.JScrollPane();
        txtPregunta2 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCpu = new javax.swing.JTextPane();
        descripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiscoDuro = new javax.swing.JTextPane();
        btnGuardar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        rbtLaptop = new javax.swing.JRadioButton();
        rbtDesktop = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CPU.setText("CPU");

        ram.setViewportView(txtRam);

        DiscoDuro.setText("Disco Duro (Mb)");

        Ram.setText("Ram (Gb)");

        precio.setViewportView(txtPrecio);

        Precio.setText("Precio");

        Descripcion.setText("Descripcion");

        preguntan1.setViewportView(txtPregunta1);

        pregunta1.setText("...");

        pregunta2.setText("...");

        preguntan2.setViewportView(txtPregunta2);

        jScrollPane1.setViewportView(txtCpu);

        descripcion.setViewportView(txtDescripcion);

        jScrollPane2.setViewportView(txtDiscoDuro);

        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setText("Equipos");

        rbtLaptop.setText("Laptop");
        rbtLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtLaptopActionPerformed(evt);
            }
        });

        rbtDesktop.setText("Desktop");
        rbtDesktop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDesktopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbtLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(rbtDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pregunta2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pregunta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CPU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Precio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Ram, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiscoDuro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(ram)
                                    .addComponent(precio)
                                    .addComponent(preguntan1)
                                    .addComponent(preguntan2)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descripcion))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Titulo)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtLaptop)
                    .addComponent(rbtDesktop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPU)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiscoDuro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ram)
                    .addComponent(ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Precio)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregunta1)
                    .addComponent(preguntan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregunta2)
                    .addComponent(preguntan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String tipoEquipo = rbtLaptop.isSelected() ? "Laptop" : "Desktop";
            String modelo = txtCpu.getText();
            int discoDuro = Integer.parseInt(txtDiscoDuro.getText());
            int ramEquipo = Integer.parseInt(txtRam.getText());
            double precioEquipo = Double.parseDouble(txtPrecio.getText());
            String pregunta1 = txtPregunta1.getText();
            String pregunta2 = txtPregunta2.getText();
            String descripcionEquipo = txtDescripcion.getText();

            validarCampoNoVacio(modelo, "CPU");
            validarNumeroPositivo(discoDuro, "Disco Duro");
            validarNumeroPositivo(ramEquipo, "RAM");
            validarNumeroPositivo(precioEquipo, "Precio");

            if (tipoEquipo.equals("Laptop")) {
                validarNumeroPositivo(Integer.parseInt(pregunta1), "Tamaño pantalla (in)");
                validarNumeroPositivo(Integer.parseInt(pregunta2), "Cantidad de puertos USB");
            } else {
                validarCampoNoVacio(pregunta1, "Fuente de poder");
                validarCampoNoVacio(pregunta2, "Factor de forma");
            }

            ControladorEquipo.registrarEquipo(tipoEquipo, modelo, discoDuro, ramEquipo, precioEquipo, pregunta1, pregunta2, descripcionEquipo);

            limpiarCampos();
            mostrarMensaje("Equipo registrado exitosamente.", "Registro Exitoso");
        } catch (NumberFormatException e) {
            mostrarError("Por favor, ingrese valores numéricos válidos.");
        } catch (Exception e) {
            mostrarError("Error al registrar el equipo. Por favor, inténtelo de nuevo.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtLaptopActionPerformed
        pregunta1.setText("Tamaño pantalla (in)");
        pregunta2.setText("Cantidad de puertos USB");
    }//GEN-LAST:event_rbtLaptopActionPerformed

    private void rbtDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDesktopActionPerformed
        pregunta1.setText("Fuente de poder");
        pregunta2.setText("Factor de forma");
    }//GEN-LAST:event_rbtDesktopActionPerformed

    private void limpiarCampos() {
    txtCpu.setText("");
    txtDiscoDuro.setText("");
    txtRam.setText("");
    txtPrecio.setText("");
    txtPregunta1.setText("");
    txtPregunta2.setText("");
    txtDescripcion.setText("");
    pregunta1.setText("...");
    pregunta2.setText("...");
    }
    
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error de Validación", JOptionPane.ERROR_MESSAGE);
    }

    private void mostrarMensaje(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    private void validarNumero(String valor, String campo) {
        try {
            int numero = Integer.parseInt(valor);
            if (numero <= 0) {
                mostrarError("Por favor, ingrese un valor numérico positivo para " + campo);
            }
        } catch (NumberFormatException e) {
            mostrarError("Por favor, ingrese un valor numérico válido para " + campo);
        }
    }

    private void validarFuenteDePoder(String valor) {
        if (valor.isEmpty()) {
            mostrarError("Por favor, ingrese información para la fuente de poder.");
        }
    }

    private void validarFactorDeForma(String valor) {
        if (valor.isEmpty()) {
            mostrarError("Por favor, ingrese información para el factor de forma.");
        }
    }
    
    private void validarCampoNoVacio(String valor, String campo) {
        if (valor.isEmpty()) {
            mostrarError("Por favor, ingrese un valor para " + campo);
        }
    }

    private void validarNumeroPositivo(double numero, String campo) {
        if (numero <= 0) {
            mostrarError("Por favor, ingrese un valor numérico positivo para " + campo);
        }
    }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPU;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel DiscoDuro;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Ram;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane descripcion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane precio;
    private javax.swing.JLabel pregunta1;
    private javax.swing.JLabel pregunta2;
    private javax.swing.JScrollPane preguntan1;
    private javax.swing.JScrollPane preguntan2;
    private javax.swing.JScrollPane ram;
    private javax.swing.JRadioButton rbtDesktop;
    private javax.swing.JRadioButton rbtLaptop;
    private javax.swing.JTextPane txtCpu;
    private javax.swing.JTextPane txtDescripcion;
    private javax.swing.JTextPane txtDiscoDuro;
    private javax.swing.JTextPane txtPrecio;
    private javax.swing.JTextPane txtPregunta1;
    private javax.swing.JTextPane txtPregunta2;
    private javax.swing.JTextPane txtRam;
    // End of variables declaration//GEN-END:variables
}
