/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Felipe
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra = new javax.swing.JMenuBar();
        Registro = new javax.swing.JMenu();
        RegistroCliente = new javax.swing.JMenuItem();
        RegistroEquipo = new javax.swing.JMenuItem();
        RegistroVenta = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        reportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registro.setText("Registros");

        RegistroCliente.setText("Registro de Cliente");
        RegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroClienteActionPerformed(evt);
            }
        });
        Registro.add(RegistroCliente);

        RegistroEquipo.setText("Registro de Equipo");
        RegistroEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroEquipoActionPerformed(evt);
            }
        });
        Registro.add(RegistroEquipo);

        RegistroVenta.setText("Registro de Venta");
        RegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroVentaActionPerformed(evt);
            }
        });
        Registro.add(RegistroVenta);

        Barra.add(Registro);

        Reportes.setText("Reportes");

        reportes.setText("Generar Reportes");
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        Reportes.add(reportes);

        Barra.add(Reportes);

        setJMenuBar(Barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroClienteActionPerformed
        System.out.println("Clic en Cliente");
        FrmCliente registroCliente = new FrmCliente();
        registroCliente.setVisible(true);
    }//GEN-LAST:event_RegistroClienteActionPerformed

    private void RegistroEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroEquipoActionPerformed
        System.out.println("Clic en Equipo");
        FrmEquipo registroEquipo = new FrmEquipo();
        registroEquipo.setVisible(true);
    }//GEN-LAST:event_RegistroEquipoActionPerformed

    private void RegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroVentaActionPerformed
        System.out.println("Clic en Venta");
        FrmVenta registroVenta = new FrmVenta();
        registroVenta.setVisible(true);
    }//GEN-LAST:event_RegistroVentaActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        System.out.println("Clic en Reportes");
        FrmReporte reporteForm = new FrmReporte();
        reporteForm.setVisible(true);
    }//GEN-LAST:event_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra;
    private javax.swing.JMenu Registro;
    private javax.swing.JMenuItem RegistroCliente;
    private javax.swing.JMenuItem RegistroEquipo;
    private javax.swing.JMenuItem RegistroVenta;
    private javax.swing.JMenu Reportes;
    private javax.swing.JMenuItem reportes;
    // End of variables declaration//GEN-END:variables
}
